### ISSUE TITLE
마이페이지 프로필사진 저장 기능 구현

### ISSUE THREAD

**Issue by chae-won-shin** [GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE#87]
### ✨ 기능 리스트

- 마이페이지 프로필 사진 저장 기능 구현

### ✏ 사용 이유

- 마이페이지 프로필 사진 저장

**Comment by KimKyuHoi** [comment]
새로운 기능 대체를 위해 이슈를 닫습니다.
